export const CHECK_AUTH = "CHECK_AUTH";

export const FETCH_AGENDA = "FETCH_AGENDA";
export const FETCH_CHILDREN = "FETCH_CHILDREN";
export const RESET_AGENDA = "RESET_AGENDA";

export const SHOW_LIST = "SHOW_LIST";
export const HIDE_LIST = "HIDE_LIST";

export const ADD_ITEM_SAVE_SUCCESS = "ADD_ITEM_SAVE_SUCCESS"; //add section
export const DEFAULT_LIST_ITEM = "DEFAULT_LIST_ITEM";
export const UPDATE_SECTION = "UPDATE_SECTION";
export const DELETE_SECTION = "DELETE_SECTION";


export const ADD_ITEM_LIST_SAVE_SUCCESS = "ADD_ITEM_LIST_SAVE_SUCCESS";


export const SHOW_LOGIN_MODAL = "SHOW_LOGIN_MODAL";
export const HIDE_LOGIN_MODAL = "HIDE_LOGIN_MODAL";
export const SHOW_DELETE_MODAL = "SHOW_DELETE_MODAL";
export const HIDE_DELETE_MODAL = "HIDE_DELETE_MODAL";
export const SHOW_ADD_SECTION_FORM_MODAL = "TOGGLE_ADD_SECTION_FORM_MODAL";
export const HIDE_ADD_SECTION_FORM_MODAL = "HIDE_ADD_SECTION_FORM_MODAL";
export const SHOW_CONTROLS = "SHOW_CONTROLS";
export const HIDE_CONTROLS = "HIDE_CONTROLS";
export const SHOW_UPDATE_SECTION_FORM = "SHOW_UPDATE_SECTION_FORM";
export const HIDE_UPDATE_SECTION_FORM = "HIDE_UPDATE_SECTION_FORM";
export const SHOW_LIST_ITEM_FORM = "SHOW_LIST_ITEM_FORM";
export const HIDE_LIST_ITEM_FORM = "HIDE_LIST_ITEM_FORM";




export const LOGIN = "LOGIN";
export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGOUT = "LOGOUT";

export const CLEAR_SYSTEM_MESSAGE = "CLEAR_SYSTEM_MESSAGE";